### ISSUE TITLE
你好，我在运行你的demo时打包出现一个错误，能帮我看看嘛

### ISSUE THREAD

**Issue by linzea** [boylegu/SpringBoot-vue#47]
ERROR org.springframework.test.context.TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@319b92f3] to prepare test instance [com.boylegu.springboot_vue.SpringbootVueApplicationTests@fa4c865]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.boylegu.springboot_vue.SpringbootVueApplicationTests': Unsatisfied dependency expressed through field 'personsRepository'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.boylegu.springboot_vue.dao.PersonsRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)

**Comment by boylegu** [comment]
不好意思，前段时间不在国内。看错误是单元测试，但很奇怪我这边都没有问题，你确定你没有进行一些修改吗，试试把单元测试代码都注视掉，在打包一下；顺便贴一下你打包的步骤
