### ISSUE TITLE
打包

### ISSUE THREAD

**Issue by Imxiaoxiaojun** [boylegu/SpringBoot-vue#52]
如果我在根目录下增加static,里面对应有js,css,images 各个文件夹以及文件，应该要怎么配置才能让这些文件打包生效呢

**Comment by boylegu** [comment]
本周我会做一个更新来帮你解决这个问题

**Comment by boylegu** [comment]
我重构了build机制，加入了不少特性，可以作为大家平时工作时生产项目的参考
